using DoctorsManagementSystem.Desktop.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace DoctorsManagementSystem.Desktop.Services;

public class PatientPdfExportService : IPatientPdfExportService
{
    public byte[] GeneratePatientReport(
        Patient patient,
        IReadOnlyList<PrescriptionSummary> prescriptions,
        IReadOnlyList<OperationSummary> operations)
    {
        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.PageColor(Colors.White);
                page.DefaultTextStyle(x => x.FontSize(10).FontColor(Colors.Grey.Darken3));

                page.Header().Column(header =>
                {
                    header.Item().Row(row =>
                    {
                        row.RelativeItem().Column(col =>
                        {
                            col.Item().Text("Doctor's Clinic Management System")
                                .FontSize(18).Bold().FontColor(Colors.Blue.Darken2);
                            col.Item().Text("Official Patient Medical Record")
                                .FontSize(11).FontColor(Colors.Grey.Darken1);
                        });

                        row.ConstantItem(150).Column(col =>
                        {
                            col.Item().AlignRight().Text($"Generated: {DateTime.Now:dd MMM yyyy}").FontSize(9);
                            col.Item().AlignRight().Text($"Report ID: PT-{patient.PatientId:D5}").FontSize(9);
                        });
                    });

                    header.Item().PaddingTop(8).LineHorizontal(1).LineColor(Colors.Blue.Darken2);
                });

                page.Content().PaddingVertical(16).Column(content =>
                {
                    content.Spacing(16);

                    content.Item().Background(Colors.Grey.Lighten4).Padding(12).Column(col =>
                    {
                        col.Item().Text("Patient Information").Bold().FontSize(13).FontColor(Colors.Blue.Darken2);
                        col.Item().PaddingTop(6).Row(row =>
                        {
                            row.RelativeItem().Column(c =>
                            {
                                c.Item().Text(t => { t.Span("Name: ").SemiBold(); t.Span(patient.PatientName); });
                                c.Item().Text(t => { t.Span("Phone: ").SemiBold(); t.Span(patient.PatientPhone); });
                            });
                            row.RelativeItem().Column(c =>
                            {
                                c.Item().Text(t =>
                                {
                                    t.Span("Email: ").SemiBold();
                                    t.Span(string.IsNullOrWhiteSpace(patient.PatientEmail) ? "—" : patient.PatientEmail);
                                });
                                c.Item().Text(t => { t.Span("Total Bill: ").SemiBold(); t.Span(patient.TotalBill.ToString("C")); });
                            });
                        });
                    });

                    content.Item().Column(col =>
                    {
                        col.Item().Text("Prescription History").Bold().FontSize(13).FontColor(Colors.Blue.Darken2);
                        col.Item().PaddingTop(6).Element(c => BuildPrescriptionsTable(c, prescriptions));
                    });

                    content.Item().Column(col =>
                    {
                        col.Item().Text("Medical Operations").Bold().FontSize(13).FontColor(Colors.Blue.Darken2);
                        col.Item().PaddingTop(6).Element(c => BuildOperationsTable(c, operations));
                    });

                    content.Item().PaddingTop(24).Row(row =>
                    {
                        row.RelativeItem();
                        row.ConstantItem(220).Column(col =>
                        {
                            col.Item().LineHorizontal(1).LineColor(Colors.Grey.Darken1);
                            col.Item().PaddingTop(4).AlignCenter().Text("Doctor's Signature")
                                .FontSize(9).FontColor(Colors.Grey.Darken1);
                        });
                    });
                });

                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("This is an official medical record generated by the clinic management system. Page ");
                    text.CurrentPageNumber();
                    text.Span(" of ");
                    text.TotalPages();
                });
            });
        });

        return document.GeneratePdf();
    }

    private static void BuildPrescriptionsTable(IContainer container, IReadOnlyList<PrescriptionSummary> prescriptions)
    {
        if (prescriptions.Count == 0)
        {
            container.Text("No prescriptions on record.").Italic().FontColor(Colors.Grey.Darken1);
            return;
        }

        container.Table(table =>
        {
            table.ColumnsDefinition(columns =>
            {
                columns.RelativeColumn(3);
                columns.RelativeColumn(2);
                columns.RelativeColumn(2);
                columns.RelativeColumn(3);
            });

            table.Header(header =>
            {
                header.Cell().Element(HeaderCell).Text("Surgery / Procedure");
                header.Cell().Element(HeaderCell).Text("Date");
                header.Cell().Element(HeaderCell).Text("Bill");
                header.Cell().Element(HeaderCell).Text("Notes");
            });

            foreach (var prescription in prescriptions)
            {
                table.Cell().Element(BodyCell).Text(prescription.SurgeryName);
                table.Cell().Element(BodyCell).Text(prescription.SessionDate.ToString("d"));
                table.Cell().Element(BodyCell).Text(prescription.SurgeryBill.ToString("C"));
                table.Cell().Element(BodyCell).Text(string.IsNullOrWhiteSpace(prescription.SurgeryNotes) ? "—" : prescription.SurgeryNotes);
            }
        });
    }

    private static void BuildOperationsTable(IContainer container, IReadOnlyList<OperationSummary> operations)
    {
        if (operations.Count == 0)
        {
            container.Text("No medical operations on record.").Italic().FontColor(Colors.Grey.Darken1);
            return;
        }

        container.Table(table =>
        {
            table.ColumnsDefinition(columns =>
            {
                columns.RelativeColumn(3);
                columns.RelativeColumn(2);
                columns.RelativeColumn(2);
                columns.RelativeColumn(3);
            });

            table.Header(header =>
            {
                header.Cell().Element(HeaderCell).Text("Operation Name");
                header.Cell().Element(HeaderCell).Text("Date");
                header.Cell().Element(HeaderCell).Text("Cost");
                header.Cell().Element(HeaderCell).Text("Doctor's Notes");
            });

            foreach (var operation in operations)
            {
                table.Cell().Element(BodyCell).Text(operation.OperationName);
                table.Cell().Element(BodyCell).Text(operation.SessionDate.ToString("d"));
                table.Cell().Element(BodyCell).Text(operation.OperationCost.ToString("C"));
                table.Cell().Element(BodyCell).Text(string.IsNullOrWhiteSpace(operation.Notes) ? "—" : operation.Notes);
            }
        });
    }

    private static IContainer HeaderCell(IContainer container) =>
        container.Background(Colors.Blue.Darken2).Padding(6).DefaultTextStyle(x => x.FontColor(Colors.White).SemiBold());

    private static IContainer BodyCell(IContainer container) =>
        container.BorderBottom(1).BorderColor(Colors.Grey.Lighten2).Padding(6);
}